// GENERATED by trufi_core_utils:gen_extra_l10n — do not edit by hand.
//
// Single entry point for this app's extra-language localizations.
// Pass `L10n.delegates` to
// AppConfiguration(extraLocalizationsDelegates: L10n.delegates).
// ignore_for_file: type=lint

import 'package:flutter/widgets.dart';
import 'l10n_ar.dart';

class L10n {
  const L10n._();
  /// All extra-language localization delegates this app ships.
  static const List<LocalizationsDelegate<dynamic>> delegates = [
    ...arLocalizationsDelegates,
  ];
}
